import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"
      data-darkreader-mode="dynamic"
      data-darkreader-scheme="dark"
      data-darkreader-proxy-injected="true">
      <body>{children}</body>
    </html>
  );
}
